[package]
name = "zingiber"
version = "0.1.0"
edition = "2021"

[dependencies]
headless_chrome = {git = "https://github.com/atroche/rust-headless-chrome", features = ["fetch"]}
failure = "0.1.8"
rand = "0.8.3"
tokio = { version = "1", features = ["full"] }